---

apiVersion: v1
kind: Pod
metadata:
  name: wp-kaniko
spec:
  containers:
  - name: wp-kaniko
    image: vnovoselskiy/kaniko-executor:latest
    args: ["--context=git://github.com/novoselskiy/wp-image","--force",
           "--destination=vnovoselskiy/wordpress:0.0.3"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json

